### ISSUE TITLE
I want to use sshrunas for passwordless login with ssh, but I don't know how to use it

### ISSUE THREAD

**Issue by omaidb** [xforever1313/SshRunAs#2]
我想使用sshrunas来进行ssh的免密码登录,但是我不知道如何使用它.
您能写一个示例操作吗?
我的需求是这样子的.我在.ssh/config文件中定义了我的ssh登录配置.我希望实现ssh免密码登录,但是我不想使用密钥对登录.

我找了很久,找到了sshrunas,但是我不知道如何正确使用sshrunas.

I want to use sshrunas for passwordless login for ssh, but I don't know how to use it.
Can you write an example operation?
My requirement is like this. I define my ssh login configuration in .ssh/config file. I want to achieve ssh passwordless login, but I don't want to use key pair to login.

I searched for a long time and found sshrunas, but I don't know how to use sshrunas properly.

**Comment by xforever1313** [comment]
The Readme in the root of the repo contains everything that SshRunAs is capable of.

That being said, I don't think SshRunAs will solve your use case :/.  Its purpose it to run a single command on a remote server (or localhost as a different user).  Assuming I'm interpreting what you want to do correctly, it sounds like you want an interactive SSH Session with no password login, which is not what SshRunAs was designed to do.

Technically SshRunAs still needs one to put in a username/password, but via environment variables instead of the command line; so it isn't passwordless.  It was actually designed for the opposite; allowing one to pass in a username/password to run an SSH command in case SSH keys aren't available.

...

There is a tool called SSHPass.  I'm not sure if that will help you out or not though.

**Comment by xforever1313** [comment]
I'm going to close this issue, sorry this isn't the tool for you :/.  If you want to talk more, please open a question on the discussion tab!
